### ISSUE TITLE
Oxford Dataset RGB Image Process

### ISSUE THREAD

**Issue by FudongGe** [jac99/MinkLocMultimodal#23]
Hi, thanks for your great work.
I have one question.
The stereo/center camera data downloaded from the official website is single-channel, but I haven't seen any code in your implementation for handling single-channel data. Did I overlook something?
Thanks in advance.

**Comment by jac99** [comment]
Hi, probably you've downloaded the wrong data. Images from the stereo-center camera are 3-channel RGB images. Take a look at  this screenshot showing exemplary images from the Bumblebee XB3 stereo camera. It shows three images: left, center and right - and all are three channel RGGB images
![image](https://github.com/jac99/MinkLocMultimodal/assets/2428126/5a224853-c31f-4c05-8c5c-0a6a6a66e467)

**Comment by FudongGe** [comment]
> Hi, probably you've downloaded the wrong data. Images from the stereo-center camera are 3-channel RGB images. Take a look at this screenshot showing exemplary images from the Bumblebee XB3 stereo camera. It shows three images: left, center and right - and all are three channel RGGB images ![image](https://private-user-images.githubusercontent.com/2428126/300219655-5a224853-c31f-4c05-8c5c-0a6a6a66e467.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MzAyMTMsIm5iZiI6MTcwNjQyOTkxMywicGF0aCI6Ii8yNDI4MTI2LzMwMDIxOTY1NS01YTIyNDg1My1jMzFmLTRjMDUtOGM1Yy0wYTZhNmE2NmU0NjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjhUMDgxODMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDFlNGI5OWMwYjRlMTNmZTJjZGYwNzgwMWU4YTA2MGQ4Yjc3N2FhNDgxMmFkNzcyN2Q4Zjg0ZWI1ODU4MzQ3YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.R6gxG4sIHwyBTQg7dkzUfYEyFeGqQ5rSlbMPz3zmjTs)

Yes, I download the data here. And it's mode is L not RGB. Is it right?

![image](https://github.com/jac99/MinkLocMultimodal/assets/110442983/5cb6dc44-36fe-4b73-9ec3-f11b30d4a29c)

**Comment by jac99** [comment]
Hi, I forgot, but it turns out that the images are stored in a special format and must be converted to RGB. See this link: https://robotcar-dataset.robots.ox.ac.uk/documentation/ in the section "Images":
All images are stored as lossless-compressed PNG files in **unrectified 8-bit raw Bayer format.** 
The top left 4 pixel Bayer pattern for the Bumblebee XB3 images is GBRG, and for Grasshopper2 images is RGGB. **The raw Bayer images can be converted to RGB using the MATLAB demosaic function, the OpenCV cvtColor function or similar methods.**

OxfordRobotCar SDK contains functions to load and decode images into RGB format. See this gitbub repo: https://github.com/ori-mrg/robotcar-dataset-sdk
The function `load_image` in `python/image.py` file loads and converts the image to RGB format.

My script `generate_rgb_for_lidar.py`, used to prepare downsampled RGB images for MinkLocMultimodal training, takes care of this and uses l`oad_image` function from RobotCar SDK to read and convert images into RGB format.

**Comment by jac99** [comment]
I've also fixed the link in README to the file with preprocessed and downsampled images from OxfordRobotCar dataset. You can use these images to train and evaluate MinkLocMultimodal method.

https://drive.google.com/file/d/1g6nWvJ-T-M41MyZTa0oRHIwP7G-cxer6/view?usp=sharing

**Comment by FudongGe** [comment]
Okay, I understand now. Thank you very much for your help！
