### ISSUE TITLE
How about the MinkLoc++ inference efficiency compared to MinkLoc3D

### ISSUE THREAD

**Issue by cgbcgb** [jac99/MinkLocMultimodal#7]
Thansk for your great work
I didn't see the introduction of inference time in paper, how about the MinkLoc++ inference efficiency compared to MinkLoc3D(22 ms per cloud) ?

**Comment by jac99** [comment]
Hi, actually MinkLoc++ inference time (for an input pair: point cloud with 4096 points + downsampled RGB image) is much lower - about 10ms. This is because MinkLoc++ uses newer , much more efficient version of MinkowskiEngine library (0.5.4) to process point clouds in a sparse voxelized representation. Inference times were measured on RTX 2080Ti and include only the time needed to process the point cloud and the image by the neural network to generate a global descriptor.
